name: Manual Approval Pipeline

on:
  workflow_dispatch:

jobs:
  approval-job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ steps.generate_token.outputs.token }}
          approvers: myteam
          minimum-approvals: 1

      - name: Proceed after approval
        run: echo "Approval received. Proceeding with the workflow."
        if: ${{ steps.wait_for_approval.outputs.approved == 'true' }}
