name: Manual Approval Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a build
        run: echo "Running build..."

  approval:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Wait for manual approval
        uses: macnev2013/manual-approval@latest
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: user1,user2
          minimum-approvals: 1
          approval-wait: 600
          issue-title: 'Aprovação Manual Necessária'
          issue-body: |
            "Por favor, aprove ou negue este workflow. A aprovação é necessária para continuar."

      - name: Echo after approval
        run: echo "Aprovação manual concluída. O fluxo de trabalho continuará agora."
